<?php
global $pages;
$pages = array(
	"accueil" => array(
		"name" =>"accueil",
		"title" => "Trium - Accueil",
		"html" => "accueil.php",
		"addr" => "accueil.html",
		"css" => array("accueil.css"),
		"keywords" => "accueil trium, index trium, accueil forum trium",
		"description" => "Le site du Forum Trium, le forum entreprises de l'écoles des ponts paristech, l'école des mines paristech, l'ENSTA et l'ENSAE",
		"scripts" => array(),
		"visible" => true,
		"a_venir" => false
	),
	"forum"  => array(
		"name" => "forum",
		"title" => "Trium - Le Forum",
		"html" => "conseils.php",
		"addr" => "forum/conseils.html",
		"css" => array("conseils.css"),
		"keywords" => "élèves, espace élèves, préparer le trium, votre trium",
		"description" => "Découvrez notre forum",
		"scripts" => array(),
		"visible" => true,
		"a_venir" => false,
		"tabs" => array(
			"presentation" => array(
				"name" => "presentation",
				"title" => "Trium - Présentation",
				"html" => "presentation.php",
				"addr" => "presentation.html",
				"css" => array(),
				"keywords" => "élèves, espace élèves, préparer le trium, votre trium",
				"description" => "Découvrez notre forum",
				"scripts" => array(),
				"visible" => false,
				"a_venir" => false,
			),
			"conseils" => array(
				"name" => "conseils",
				"title" => "Trium - conseils",
				"html" => "conseils.php",
				"addr" => "conseils.html",
				"css" => array("conseils.css"),
				"keywords" => "élèves, espace élèves, préparer le trium, votre trium",
				"description" => "Découvrez notre forum",
				"scripts" => array(),
				"visible" => false,
				"a_venir" => false,
			),
			"deroulement" => array(
				"name" => "deroulement",
				"title" => "Trium - Déroulement",
				"html" => "deroulement.php",
				"addr" => "deroulement.html",
				"css" => array("deroulement.css"),
				"keywords" => "élèves, espace élèves, préparer le trium, votre trium",
				"description" => "Découvrez notre forum",
				"scripts" => array(),
				"visible" => false,
				"a_venir" => false,
			)
		)
	),
	"ecoles"  => array(
		"name" => "ecoles",
		"title" => "Trium - Écoles",
		"html" => "ecoles.php",
		"addr" => "ecoles.html",
		"css" => array(),
		"keywords" => "écoles, les écoles, ponts, enpc, les ponts, les ponts et chaussées, ensta, école nationale supérieure des techniques avancées, mines, mines paris, mines de paris, mines paristech, les mines de paris, les mines, ensae",
		"description" => "Découvrez les écoles organisatrices",
		"scripts" => array(),
		"visible" => true,
		"a_venir" => false
	),
	"eleves"  => array(
		"name" => "eleves",
		"title" => "Trium - Élèves",
		"html" => "eleves.php",
		"addr" => "eleves.html",
		"css" => array("eleves.css"),
		"keywords" => "élèves, espace élèves, préparer le trium, votre trium",
		"description" => "Espace élèves, préparez votre forum Trium",
		"scripts" => array(),
		"visible" => false,
		"a_venir" => true
	),
	"entreprises"  => array(
		"name" => "entreprises",
		"title" => "Trium - Entreprises",
		"html" => "entreprises.php",
		"addr" => "entreprises.html",
		"css" => array("entreprises.css"),
		"keywords" => "entreprises, espace entreprises, cereza conseil, ubisoft, peugot, psa, alten, EY, ernst ande young, ernst & young, otis, vinci, freyssinet, théodo, theodo",
		"description" => "Espace entreprises, venez découvrir les exposants",
		"scripts" => array("entreprises.js"),
		"visible" => true,
		"a_venir" => false
	),
	"partenaires"  => array(
		"name" => "partenaires",
		"title" => "Trium - Partenaires",
		"html" => "partenaires.php",
		"addr" => "partenaires.html",
		"css" => array("partenaires.css"),
		"keywords" => "partenaires trium, l'étudiant, le monde, le figaro",
		"description" => "Tous les partenariats du Forum Trium",
		"scripts" => array(),
		"visible" => true,
		"a_venir" => false
	),
	"contact"  => array(
		"name" => "contact",
		"title" => "Trium - Contacts",
		"html" => "contact.php",
		"addr" => "contact.html",
		"css" => array("contact.css"),
		"keywords" => "nous contacter, contacter forum trium, contacter trium, contacter le forum trium, contacter le trium",
		"description" => "Comment contacter le Forum Trium",
		"scripts" => array(),
		"visible" => true,
		"a_venir" => false
	),
	"besttriumever"  => array(
		"name" => "besttriumever",
		"title" => "Trium - Best Trium Ever",
		"html" => "easterEgg.php",
		"addr" => "besttriumever.html",
		"css" => array("contact.css"),
		"keywords" => "easter egg",
		"description" => "Easter Egg",
		"scripts" => array(),
		"visible" => false,
		"a_venir" => false
	),
	"404"  => array(
		"name" => "404",
		"title" => "Trium - Erreur 404",
		"html" => "404.php",
		"addr" => "404.html",
		"css" => array("404.css"),
		"keywords" => "",
		"description" => "Erreur 404",
		"scripts" => array(),
		"visible" => false,
		"a_venir" => false
	),
	"403"  => array(
		"name" => "403",
		"title" => "Trium - Erreur 403",
		"html" => "403.php",
		"addr" => "403.html",
		"css" => array("403.css"),
		"keywords" => "",
		"description" => "Erreur 403",
		"scripts" => array(),
		"visible" => false,
		"a_venir" => false
	),
	"a_venir"  => array(
		"name" => "a_venir",
		"title" => "Trium - À venir",
		"html" => "a_venir.php",
		"addr" => "a_venir.html",
		"css" => array("a_venir.css"),
		"keywords" => "",
		"description" => "Contenu à venir",
		"scripts" => array(),
		"visible" => false,
		"a_venir" => false
	)
);
